# Generated by Django 5.2.8 on 2025-11-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
