# Generated by Django 5.2.8 on 2025-11-15 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Beverage', 'Beverage'), ('Meal', 'Meal'), ('Non-Veg', 'Non-Veg'), ('Snacks', 'Snacks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
